apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - deployment.yaml
    - inferencepool.yaml
    - service.yaml
    - secrets.yaml
    - referencegrant.yaml
    - v1-route.yaml

configurations:
    - configurations.yaml

# Default config
configMapGenerator:
    - name: model-config
      literals:
          - MODEL_NAME=base-model
          - MODEL_ID=base-model-id
          - COMPUTE_CLASS=dws-flex-h100
          - NEG_NAME=base-model-neg
          - POOL_NAME=base-pool
          - MODEL_NAMESPACE=inference-gateway
          - PROJECT_ID=PLACEHOLDER_PROJECT_ID
      options:
          disableNameSuffixHash: true
          labels:
              inference.gke.io/kind: model-config
