apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - base
  - apigee-backend-service.yaml
  - apigee-apim-operator-helm.gen.yaml

replacements:
  - source:
      kind: ConfigMap
      name: gateway-env-config
      fieldPath: data.APIGEE_ENV
    targets:
      - select:
          kind: ApigeeBackendService
          name: apigee-cache-backend
        fieldPaths:
          - spec.apigeeEnv

  - source:
      kind: ConfigMap
      name: gateway-env-config
      fieldPath: data.REGION
    targets:
      - select:
          kind: ApigeeBackendService
          name: apigee-cache-backend
        fieldPaths:
          - spec.locations.0.name

  - source:
      kind: ConfigMap
      name: gateway-env-config
      fieldPath: data.VPC_NETWORK
    targets:
      - select:
          kind: ApigeeBackendService
          name: apigee-cache-backend
        fieldPaths:
          - spec.locations.0.network

  - source:
      kind: ConfigMap
      name: gateway-env-config
      fieldPath: data.VPC_SUBNET
    targets:
      - select:
          kind: ApigeeBackendService
          name: apigee-cache-backend
        fieldPaths:
          - spec.locations.0.subnetwork
