apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../semantic-cache-infra

resources:
  - semantic-cache-extension.yaml

replacements:
  - source:
      kind: ConfigMap
      name: gateway-env-config
      fieldPath: data.SEMANTIC_PROXY_NAME
    targets:
      - select:
          kind: GCPTrafficExtension
          name: semantic-cache-extension
        fieldPaths:
          - spec.extensionChains.0.extensions.0.metadata.apigee-extension-processor
