---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: apigee-apim-operator
    provider: jkube
    version: 1.0.0
    group: com.apigee
  name: apim-operator-role-binding
  namespace: apim
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: apim-operator-role
subjects:
- kind: ServiceAccount
  name: apim-ksa
  namespace: apim
