---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ required "Error: Supply your GCP service_account with '--set serviceAccount=...'" .Values.serviceAccount | quote }}
  labels:
    app: apigee-apim-operator
    provider: jkube
    version: 1.0.0
    group: com.apigee
  name: apim-ksa
  namespace: apim
